### ISSUE TITLE
闪退问题

### ISSUE THREAD

**Issue by zyxsjdy** [nxs7/WA2-CHS-Subtitle-Patch#1]
作者大大您好，我这里在加了您的字幕之后会出现游戏崩溃的问题，如果不加就没问题（win10）。我也不太能理解是什么原因导致的。

**Comment by nxs7** [comment]
请尝试删除或重命名游戏目录下的mv*.pak文件，检查问题是否持续。

**Comment by zyxsjdy** [comment]
感谢回复。删除之后，打开游戏时会提示缺失这个文件，但是游戏可以正常运行并且字幕也正常显示。

**Comment by zyxsjdy** [comment]
但是这个方法仅在special contents部分有用，游戏本体部分不行。
如果我没理解错的话，[patch-v0.3-specialcontents.zip]是给special contents部分做的字幕，[patch-v0.3.zip]是给游戏本体做的字幕？

**Comment by nxs7** [comment]
是的。另外，这当然不是最终解决方案XD，我只是想确认问题的来源。
这个补丁目前与某些硬件解码器不兼容，如LAV Filters。如果您安装了这类解码器，请考虑将其卸载。
我稍后会更新自述文档说明这个问题。

**Comment by zyxsjdy** [comment]
OK，应该就是这玩意的问题了，我卸载LAV Filters后完美运行。麻烦您啦！
